import { ParserLog } from '@ditrit/leto-modelizer-plugin-core';

const errors = [
  new ParserLog({
    path: 'parserError.tf',
    componentId: null,
    attribute: null,
    startLineNumber: 13,
    startColumn: 1,
    endLineNumber: 13,
    endColumn: 7,
    message: 'parser.error.parsing',
    severity: ParserLog.SEVERITY_ERROR,
    initialErrorMessage: 'extraneous input \'blabla\' expecting {<EOF>, \'terraform\', \'resource\', \'data\', \'output\', \'locals\', \'module\', \'variable\', \'provider\'}',
  }),
  new ParserLog({
    path: 'parserError.tf',
    componentId: 'id_1',
    attribute: 'load_balancing_algorithm_type',
    startLineNumber: 2,
    startColumn: 35,
    endLineNumber: 2,
    endColumn: 40,
    message: 'parser.error.invalidValue',
    severity: ParserLog.SEVERITY_ERROR,
    initialErrorMessage: null,
    extraData: 'round_robin, least_outstanding_requests',
  }),
  new ParserLog({
    path: 'parserError.tf',
    componentId: 'id_2',
    attribute: 'load_balancing_algorithm_type',
    startLineNumber: 6,
    startColumn: 35,
    endLineNumber: 6,
    endColumn: 36,
    message: 'parser.error.notString',
    severity: ParserLog.SEVERITY_ERROR,
    initialErrorMessage: null,
  }),
  new ParserLog({
    path: 'parserError.tf',
    componentId: 'id_2',
    attribute: 'load_balancing_algorithm_type',
    startLineNumber: 6,
    startColumn: 35,
    endLineNumber: 6,
    endColumn: 36,
    message: 'parser.error.invalidValue',
    severity: ParserLog.SEVERITY_ERROR,
    initialErrorMessage: null,
    extraData: 'round_robin, least_outstanding_requests',
  }),
  new ParserLog({
    path: 'parserError.tf',
    componentId: 'id_3',
    attribute: null,
    startLineNumber: 9,
    startColumn: 10,
    endLineNumber: 9,
    endColumn: 19,
    message: 'parser.warning.noComponentDefinition',
    severity: ParserLog.SEVERITY_WARNING,
    initialErrorMessage: null,
  }),
  new ParserLog({
    path: 'parserError.tf',
    componentId: 'id_4',
    attribute: null,
    startLineNumber: 11,
    startColumn: 32,
    endLineNumber: 11,
    endColumn: 34,
    message: '@ditrit/terrator-plugin.parser.error.noExternalId',
    severity: ParserLog.SEVERITY_ERROR,
    initialErrorMessage: null,
  }),
  new ParserLog({
    path: 'parserError.tf',
    componentId: 'id_5',
    attribute: 'region',
    startLineNumber: 15,
    startColumn: 1,
    endLineNumber: 15,
    endColumn: 32,
    message: 'parser.error.required',
    severity: ParserLog.SEVERITY_ERROR,
    initialErrorMessage: null,
  }),
  new ParserLog({
    path: 'parserError.tf',
    componentId: 'id_6',
    attribute: 'target_group_arn',
    startLineNumber: 21,
    startColumn: 25,
    endLineNumber: 21,
    endColumn: 36,
    message: '@ditrit/terrator-plugin.parser.error.badExternalId',
    severity: ParserLog.SEVERITY_ERROR,
    initialErrorMessage: null,
    extraData: 'lb_target',
  }),
];

export default errors;
